import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { api } from '../api'
import '../styles/Step2EnvSetup.css'

type LogLine = { time: string; msg: string }

type Props = {
  simulationId?: string
  projectData: { project_id?: string; graph_id?: string } | null
  graphData?: unknown
  systemLogs: LogLine[]
  onGoBack: () => void
  onNextStep: (params: { maxRounds?: number }) => void
  onAddLog: (msg: string) => void
  onUpdateStatus: (s: 'processing' | 'completed' | 'error') => void
}

export default function Step2EnvSetup({
  simulationId,
  projectData,
  systemLogs,
  onGoBack,
  onNextStep,
  onAddLog,
  onUpdateStatus
}: Props) {
  const [phase, setPhase] = useState(0)
  const [taskId, setTaskId] = useState<string | null>(null)
  const [prepareProgress, setPrepareProgress] = useState(0)
  const [currentStage, setCurrentStage] = useState('')
  const [profiles, setProfiles] = useState<Record<string, unknown>[]>([])
  const [expectedTotal, setExpectedTotal] = useState<number | null>(null)
  const [simulationConfig, setSimulationConfig] = useState<Record<string, unknown> | null>(null)
  const [selectedProfile, setSelectedProfile] = useState<Record<string, unknown> | null>(null)
  const [useCustomRounds, setUseCustomRounds] = useState(false)
  const [customMaxRounds, setCustomMaxRounds] = useState(40)

  const logContentRef = useRef<HTMLDivElement>(null)
  const lastProgressDetailKeyRef = useRef('')
  const lastStatusMessageRef = useRef('')
  const lastLoggedProfileCountRef = useRef(0)
  const lastLoggedConfigStageRef = useRef('')

  const pollTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const profilesTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const configTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const autoGeneratedRounds = useMemo(() => {
    const tc = simulationConfig?.time_config as Record<string, number> | undefined
    if (!tc?.total_simulation_hours || !tc?.minutes_per_round) return null
    return Math.max(Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round), 40)
  }, [simulationConfig])

  const totalTopicsCount = useMemo(
    () =>
      profiles.reduce((sum, p) => {
        const topics = p.interested_topics as string[] | undefined
        return sum + (topics?.length ?? 0)
      }, 0),
    [profiles]
  )

  const stopPolling = useCallback(() => {
    if (pollTimerRef.current) {
      clearInterval(pollTimerRef.current)
      pollTimerRef.current = null
    }
  }, [])

  const stopProfilesPolling = useCallback(() => {
    if (profilesTimerRef.current) {
      clearInterval(profilesTimerRef.current)
      profilesTimerRef.current = null
    }
  }, [])

  const stopConfigPolling = useCallback(() => {
    if (configTimerRef.current) {
      clearInterval(configTimerRef.current)
      configTimerRef.current = null
    }
  }, [])

  const fetchProfilesRealtime = useCallback(async () => {
    if (!simulationId) return
    try {
      const res = await api.simulation.getProfilesRealtime(simulationId, 'reddit')
      if (res.success && res.data) {
        const list = (res.data.profiles as Record<string, unknown>[]) || []
        setProfiles(list)
        if (res.data.total_expected) setExpectedTotal(res.data.total_expected as number)

        const currentCount = list.length
        if (currentCount > 0 && currentCount !== lastLoggedProfileCountRef.current) {
          lastLoggedProfileCountRef.current = currentCount
          const total = (res.data.total_expected as number | undefined) ?? expectedTotal ?? '?'
          const latest = list[currentCount - 1] || {}
          const profileName = (latest.name as string) || (latest.username as string) || `Agent_${currentCount}`
          if (currentCount === 1) onAddLog(`Start generationAgentPersona...`)
          onAddLog(
            `→ AgentPersona ${currentCount}/${total}: ${profileName} (${(latest.profession as string) || 'Unknown Profession'})`
          )
          const exp = res.data.total_expected as number | undefined
          if (exp && currentCount >= exp) {
            onAddLog(`✓ All (All) ${currentCount} NumberAgentPersona generation completed`)
          }
        }
      }
    } catch {
      /* ignore */
    }
  }, [simulationId, expectedTotal, onAddLog])

  const fetchConfigRealtime = useCallback(async () => {
    if (!simulationId) return
    try {
      const res = await api.simulation.getConfigRealtime(simulationId)
      if (res.success && res.data) {
        const data = res.data as Record<string, unknown>
        const genStage = data.generation_stage as string | undefined
        if (genStage && genStage !== lastLoggedConfigStageRef.current) {
          lastLoggedConfigStageRef.current = genStage
          if (genStage === 'generating_profiles') onAddLog('CurrentlyGenerateAgentPersona Configuration...')
          else if (genStage === 'generating_config') onAddLog('CallingLLMGenerate Simulation ConfigurationParameter...')
        }
        if (data.config_generated && data.config) {
          setSimulationConfig(data.config as Record<string, unknown>)
          onAddLog('✓ Simulation configuration generation completed')
          const summary = data.summary as Record<string, unknown> | undefined
          if (summary) {
            onAddLog(`  ├─ AgentQuantity: ${summary.total_agents}Number`)
            onAddLog(`  ├─ Simulation Duration: ${summary.simulation_hours}hours`)
            onAddLog(`  ├─ Initial posts: ${summary.initial_posts_count}items`)
            onAddLog(
              `  └─ Platform configuration: Twitter ${summary.has_twitter_config ? '✓' : '✗'}, Reddit ${summary.has_reddit_config ? '✓' : '✗'}`
            )
          }
          const tc = (data.config as Record<string, unknown>).time_config as Record<string, number> | undefined
          if (tc) {
            onAddLog(
              `Time Configuration: Per round${tc.minutes_per_round}minutes, Total${Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round)}rounds`
            )
          }
          const ec = (data.config as Record<string, unknown>).event_config as { narrative_direction?: string } | undefined
          if (ec?.narrative_direction) {
            const narrative = ec.narrative_direction
            onAddLog(`Narrative Direction: ${narrative.length > 50 ? narrative.substring(0, 50) + '...' : narrative}`)
          }
          stopConfigPolling()
          setPhase(4)
          onAddLog('✓ Env Setup Completed，Can start simulation')
          onUpdateStatus('completed')
        }
      }
    } catch {
      /* ignore */
    }
  }, [simulationId, onAddLog, onUpdateStatus, stopConfigPolling])

  const startConfigPolling = useCallback(() => {
    if (configTimerRef.current) return
    configTimerRef.current = setInterval(() => void fetchConfigRealtime(), 2000)
  }, [fetchConfigRealtime])

  const loadPreparedData = useCallback(async () => {
    if (!simulationId) return
    setPhase(2)
    onAddLog('Loading existing configuration data...')
    try {
      const pr = await api.simulation.getProfilesRealtime(simulationId, 'reddit')
      if (pr.success && pr.data) {
        setProfiles((pr.data.profiles as Record<string, unknown>[]) || [])
        if (pr.data.total_expected) setExpectedTotal(pr.data.total_expected as number)
        const n = (pr.data.profiles as unknown[])?.length ?? 0
        onAddLog(`Loaded ${n} NumberAgentPersona`)
      }
    } catch {
      onAddLog('Loaded agent personas (count unavailable)')
    }

    try {
      const res = await api.simulation.getConfigRealtime(simulationId)
      if (res.success && res.data) {
        if (res.data.config_generated && res.data.config) {
          setSimulationConfig(res.data.config as Record<string, unknown>)
          onAddLog('✓ Simulation configuration loaded successfully')
          if (res.data.summary) {
            const s = res.data.summary as Record<string, unknown>
            onAddLog(`  ├─ AgentQuantity: ${s.total_agents}Number`)
            onAddLog(`  ├─ Simulation Duration: ${s.simulation_hours}hours`)
            onAddLog(`  └─ Initial posts: ${s.initial_posts_count}items`)
          }
          onAddLog('✓ Env Setup Completed，Can start simulation')
          setPhase(4)
          onUpdateStatus('completed')
        } else {
          onAddLog('Configuration generating，Start polling wait...')
          startConfigPolling()
        }
      }
    } catch (err: unknown) {
      const m = err instanceof Error ? err.message : String(err)
      onAddLog(`Failed to load configuration: ${m}`)
      onUpdateStatus('error')
    }
  }, [onAddLog, onUpdateStatus, simulationId, startConfigPolling])

  useEffect(() => {
    if (currentStage === 'GenerateAgentPersona' || currentStage === 'generating_profiles') {
      setPhase(1)
    } else if (currentStage === 'Generate Simulation Configuration' || currentStage === 'generating_config') {
      setPhase(2)
      if (!configTimerRef.current) {
        onAddLog('Start generating dual platform simulation configuration...')
        startConfigPolling()
      }
    } else if (currentStage === 'Prepare simulation script' || currentStage === 'copying_scripts') {
      setPhase(2)
    }
  }, [currentStage, onAddLog, startConfigPolling])

  const pollPrepareStatus = useCallback(async () => {
    if (!taskId && !simulationId) return
    try {
      const res = await api.simulation.getPrepareStatus({ task_id: taskId, simulation_id: simulationId })
      if (res.success && res.data) {
        const data = res.data as Record<string, unknown>
        setPrepareProgress((data.progress as number) || 0)
        const pd = data.progress_detail as Record<string, unknown> | undefined
        if (pd) {
          setCurrentStage((pd.current_stage_name as string) || '')
          const detail = pd
          const logKey = `${detail.current_stage}-${detail.current_item}-${detail.total_items}`
          if (logKey !== lastProgressDetailKeyRef.current && detail.item_description) {
            lastProgressDetailKeyRef.current = logKey
            const stageInfo = `[${detail.stage_index}/${detail.total_stages}]`
            if ((detail.total_items as number) > 0) {
              onAddLog(
                `${stageInfo} ${detail.current_stage_name}: ${detail.current_item}/${detail.total_items} - ${detail.item_description}`
              )
            } else {
              onAddLog(`${stageInfo} ${detail.current_stage_name}: ${detail.item_description}`)
            }
          }
        } else if (data.message) {
          const match = String(data.message).match(/\[(\d+)\/(\d+)\]\s*([^:]+)/)
          if (match) setCurrentStage(match[3].trim())
          if (data.message !== lastStatusMessageRef.current) {
            lastStatusMessageRef.current = data.message as string
            onAddLog(data.message as string)
          }
        }
        if (data.status === 'completed' || data.status === 'ready' || data.already_prepared) {
          onAddLog('✓ Preparation work completed')
          stopPolling()
          stopProfilesPolling()
          await loadPreparedData()
        } else if (data.status === 'failed') {
          onAddLog(`✗ Preparation failed: ${data.error || 'Unknown error'}`)
          stopPolling()
          stopProfilesPolling()
        }
      }
    } catch {
      /* ignore */
    }
  }, [taskId, simulationId, onAddLog, stopPolling, stopProfilesPolling, loadPreparedData])

  const startPolling = useCallback(() => {
    pollTimerRef.current = setInterval(() => void pollPrepareStatus(), 2000)
  }, [pollPrepareStatus])

  const startProfilesPolling = useCallback(() => {
    profilesTimerRef.current = setInterval(() => void fetchProfilesRealtime(), 3000)
  }, [fetchProfilesRealtime])

  const startPrepareSimulation = useCallback(async () => {
    if (!simulationId) {
      onAddLog('Error：Missing simulationId')
      onUpdateStatus('error')
      return
    }
    setPhase(1)
    onAddLog(`Simulation instance created: ${simulationId}`)
    onAddLog('Preparing simulation environment...')
    onUpdateStatus('processing')
    try {
      const res = await api.simulation.prepare({
        simulation_id: simulationId,
        use_llm_for_profiles: true,
        parallel_profile_count: 5
      })
      if (res.success && res.data) {
        if (res.data.already_prepared) {
          onAddLog('Detected existing completed preparation work，Use directly')
          await loadPreparedData()
          return
        }
        setTaskId(res.data.task_id as string)
        onAddLog(`Preparation task started`)
        onAddLog(`  └─ Task ID: ${res.data.task_id}`)
        if (res.data.expected_entities_count) {
          setExpectedTotal(res.data.expected_entities_count as number)
          onAddLog(`FromNeo4jGraph read ${res.data.expected_entities_count} entities`)
          const et = res.data.entity_types as string[] | undefined
          if (et?.length) onAddLog(`  └─ Entity Type: ${et.join(', ')}`)
        }
        onAddLog('Start polling preparation progress...')
        startPolling()
        startProfilesPolling()
      } else {
        onAddLog(`Preparation failed: ${res.error || 'Unknown error'}`)
        onUpdateStatus('error')
      }
    } catch (err: unknown) {
      const m = err instanceof Error ? err.message : String(err)
      onAddLog(`Preparation exception: ${m}`)
      onUpdateStatus('error')
    }
  }, [simulationId, onAddLog, onUpdateStatus, loadPreparedData, startPolling, startProfilesPolling])

  useEffect(() => {
    if (simulationId) {
      onAddLog('Step2 Env Setup Initialization')
      void startPrepareSimulation()
    }
    return () => {
      stopPolling()
      stopProfilesPolling()
      stopConfigPolling()
    }
  }, [simulationId])

  useEffect(() => {
    const el = logContentRef.current
    if (el) el.scrollTop = el.scrollHeight
  }, [systemLogs.length])

  const handleStartSimulation = () => {
    if (useCustomRounds) {
      onAddLog(`Start simulation，Custom rounds: ${customMaxRounds} rounds`)
      onNextStep({ maxRounds: customMaxRounds })
    } else {
      onAddLog(`Start simulation，Use auto-configured rounds: ${autoGeneratedRounds} rounds`)
      onNextStep({})
    }
  }

  const getAgentUsername = (agentId: number) => {
    if (profiles.length > agentId && agentId >= 0) {
      const profile = profiles[agentId]
      return (profile?.username as string) || `agent_${agentId}`
    }
    return `agent_${agentId}`
  }

  const tc = simulationConfig?.time_config as Record<string, unknown> | undefined
  const eventCfg = simulationConfig?.event_config as Record<string, unknown> | undefined

  return (
    <div className="env-setup-panel">
      <div className="scroll-container">
        <div className={`step-card${phase === 0 ? ' active' : ''}${phase > 0 ? ' completed' : ''}`}>
          <div className="card-header">
            <div className="step-info">
              <span className="step-num">01</span>
              <span className="step-title">Simulation Instance Initialization</span>
            </div>
            <div className="step-status">
              {phase > 0 ? <span className="badge success">Completed</span> : <span className="badge processing">Initialization</span>}
            </div>
          </div>
          <div className="card-content">
            <p className="api-note">POST /api/simulation/create</p>
            <p className="description">Create new simulation instance and fetch simulated world parameter template</p>
            {simulationId && (
              <div className="info-card">
                <div className="info-row">
                  <span className="info-label">Project ID</span>
                  <span className="info-value mono">{projectData?.project_id}</span>
                </div>
                <div className="info-row">
                  <span className="info-label">Graph ID</span>
                  <span className="info-value mono">{projectData?.graph_id}</span>
                </div>
                <div className="info-row">
                  <span className="info-label">Simulation ID</span>
                  <span className="info-value mono">{simulationId}</span>
                </div>
                <div className="info-row">
                  <span className="info-label">Task ID</span>
                  <span className="info-value mono">{taskId || 'Async task completed'}</span>
                </div>
              </div>
            )}
          </div>
        </div>

        <div className={`step-card${phase === 1 ? ' active' : ''}${phase > 1 ? ' completed' : ''}`}>
          <div className="card-header">
            <div className="step-info">
              <span className="step-num">02</span>
              <span className="step-title">Generate Agent Personas</span>
            </div>
            <div className="step-status">
              {phase > 1 ? (
                <span className="badge success">Completed</span>
              ) : phase === 1 ? (
                <span className="badge processing">{prepareProgress}%</span>
              ) : (
                <span className="badge pending">Waiting</span>
              )}
            </div>
          </div>
          <div className="card-content">
            <p className="api-note">POST /api/simulation/prepare</p>
            <p className="description">
              Combined with context, tools organize entities from the knowledge graph and initialize simulation individuals.
            </p>
            {profiles.length > 0 && (
              <div className="stats-grid">
                <div className="stat-card">
                  <span className="stat-value">{profiles.length}</span>
                  <span className="stat-label">Current Agent Count</span>
                </div>
                <div className="stat-card">
                  <span className="stat-value">{expectedTotal ?? '-'}</span>
                  <span className="stat-label">Expected Agent Total</span>
                </div>
                <div className="stat-card">
                  <span className="stat-value">{totalTopicsCount}</span>
                  <span className="stat-label">Related Topics</span>
                </div>
              </div>
            )}
            {profiles.length > 0 && (
              <div className="profiles-preview">
                <div className="preview-header">
                  <span className="preview-title">Generated Agent Personas</span>
                </div>
                <div className="profiles-list">
                  {profiles.slice(0, 12).map((profile, idx) => (
                    <div key={idx} className="profile-card" onClick={() => setSelectedProfile(profile)} role="button" tabIndex={0}>
                      <div className="profile-header">
                        <span className="profile-realname">{(profile.username as string) || 'Unknown'}</span>
                        <span className="profile-username">@{(profile.name as string) || `agent_${idx}`}</span>
                      </div>
                      <div className="profile-meta">
                        <span className="profile-profession">{(profile.profession as string) || 'Unknown Profession'}</span>
                      </div>
                      <p className="profile-bio">
                        {String(profile.bio || 'No introduction available').length > 80
                          ? String(profile.bio).substring(0, 80) + '...'
                          : String(profile.bio || 'No introduction available')}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        <div className={`step-card${phase === 2 ? ' active' : ''}${phase > 2 ? ' completed' : ''}`}>
          <div className="card-header">
            <div className="step-info">
              <span className="step-num">03</span>
              <span className="step-title">Simulation Configuration</span>
            </div>
            <div className="step-status">
              {phase > 2 ? (
                <span className="badge success">Completed</span>
              ) : phase === 2 ? (
                <span className="badge processing">Generating</span>
              ) : (
                <span className="badge pending">Waiting</span>
              )}
            </div>
          </div>
          <div className="card-content">
            <p className="api-note">POST /api/simulation/prepare</p>
            {simulationConfig && tc && (
              <div className="config-detail-panel">
                <div className="config-grid">
                  <div className="config-item">
                    <span className="config-item-label">Simulation Duration</span>
                    <span className="config-item-value">{String(tc.total_simulation_hours ?? '-')} hours</span>
                  </div>
                  <div className="config-item">
                    <span className="config-item-label">Duration per round</span>
                    <span className="config-item-value">{String(tc.minutes_per_round ?? '-')} minutes</span>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        <div className={`step-card${phase === 3 ? ' active' : ''}${phase > 3 ? ' completed' : ''}`}>
          <div className="card-header">
            <div className="step-info">
              <span className="step-num">04</span>
              <span className="step-title">Initial activation arrangement</span>
            </div>
            <div className="step-status">
              {phase > 3 ? (
                <span className="badge success">Completed</span>
              ) : phase === 3 ? (
                <span className="badge processing">Arranging</span>
              ) : (
                <span className="badge pending">Waiting</span>
              )}
            </div>
          </div>
          <div className="card-content">
            {eventCfg && (
              <div className="orchestration-content">
                <div className="narrative-box">
                  <span className="box-label narrative-label">Narrative Guidance Direction</span>
                  <p className="narrative-text">{String(eventCfg.narrative_direction || '')}</p>
                </div>
                {Array.isArray(eventCfg.hot_topics) && (
                  <div className="topics-section">
                    <span className="box-label">Initial trending topics</span>
                    <div className="hot-topics-grid">
                      {(eventCfg.hot_topics as string[]).map((topic) => (
                        <span key={topic} className="hot-topic-tag">
                          # {topic}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {Array.isArray(eventCfg.initial_posts) && (
                  <div className="initial-posts-section">
                    <span className="box-label">Initial activation sequence ({(eventCfg.initial_posts as unknown[]).length})</span>
                    <div className="posts-timeline">
                      {(eventCfg.initial_posts as Record<string, unknown>[]).map((post, idx) => (
                        <div key={idx} className="timeline-item">
                          <div className="timeline-marker" />
                          <div className="timeline-content">
                            <div className="post-header">
                              <span className="post-role">{String(post.poster_type)}</span>
                              <span className="post-agent-info">
                                <span className="post-id">Agent {String(post.poster_agent_id)}</span>
                                <span className="post-username">@{getAgentUsername(Number(post.poster_agent_id))}</span>
                              </span>
                            </div>
                            <p className="post-text">{String(post.content)}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        <div className={`step-card${phase === 4 ? ' active' : ''}`}>
          <div className="card-header">
            <div className="step-info">
              <span className="step-num">05</span>
              <span className="step-title">Preparation completed</span>
            </div>
            <div className="step-status">
              {phase >= 4 ? <span className="badge processing">In progress</span> : <span className="badge pending">Waiting</span>}
            </div>
          </div>
          <div className="card-content">
            <p className="api-note">POST /api/simulation/start</p>
            {simulationConfig && autoGeneratedRounds && (
              <div className="rounds-config-section">
                <div className="rounds-header">
                  <div className="header-left">
                    <span className="section-title">Simulation Rounds Setting</span>
                  </div>
                  <label className="switch-control">
                    <input type="checkbox" checked={useCustomRounds} onChange={(e) => setUseCustomRounds(e.target.checked)} />
                    <span className="switch-track" />
                    <span className="switch-label">Custom</span>
                  </label>
                </div>
                {useCustomRounds ? (
                  <div className="rounds-content custom">
                    <div className="range-wrapper">
                      <input
                        type="range"
                        min={10}
                        max={autoGeneratedRounds}
                        step={5}
                        value={customMaxRounds}
                        onChange={(e) => setCustomMaxRounds(Number(e.target.value))}
                        className="minimal-slider"
                      />
                      <div className="slider-main-value">
                        <span className="val-num">{customMaxRounds}</span>
                        <span className="val-unit">rounds</span>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="rounds-content auto">
                    <div className="auto-value">
                      <span className="val-num">{autoGeneratedRounds}</span>
                      <span className="val-unit">rounds</span>
                    </div>
                  </div>
                )}
              </div>
            )}
            <div className="action-group dual">
              <button type="button" className="action-btn secondary" onClick={onGoBack}>
                ← Return graph construction
              </button>
              <button type="button" className="action-btn primary" disabled={phase < 4} onClick={handleStartSimulation}>
                Start dual world parallel simulation ➝
              </button>
            </div>
          </div>
        </div>
      </div>

      {selectedProfile && (
        <div className="profile-modal-overlay" onClick={() => setSelectedProfile(null)} role="presentation">
          <div className="profile-modal" onClick={(e) => e.stopPropagation()} role="dialog">
            <div className="modal-header">
              <div className="modal-header-info">
                <div className="modal-name-row">
                  <span className="modal-realname">{String(selectedProfile.username)}</span>
                  <span className="modal-username">@{String(selectedProfile.name)}</span>
                </div>
                <span className="modal-profession">{String(selectedProfile.profession)}</span>
              </div>
              <button type="button" className="close-btn" onClick={() => setSelectedProfile(null)}>
                ×
              </button>
            </div>
            <div className="modal-body">
              <p className="section-bio">{String(selectedProfile.bio || '')}</p>
            </div>
          </div>
        </div>
      )}

      <div className="system-logs">
        <div className="log-header">
          <span className="log-title">SYSTEM DASHBOARD</span>
          <span className="log-id">{simulationId || 'NO_SIMULATION'}</span>
        </div>
        <div className="log-content" ref={logContentRef}>
          {systemLogs.map((log, idx) => (
            <div key={idx} className="log-line">
              <span className="log-time">{log.time}</span>
              <span className="log-msg">{log.msg}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
